(function(){
'use strict';
const state={vehicles:[],refs:[],gps:[],plans:[],services:[],fuel:[],fuelRefs:[],request:0};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>v===null||v===undefined||v===''?null:Number(v);
const fmt=v=>v===null||v===undefined?'—':Number(v).toLocaleString('tr-TR',{maximumFractionDigits:0});
const date=v=>v?new Date(v).toLocaleString('tr-TR'):'—';
const localNow=()=>new Date(Date.now()+10800000).toISOString().slice(0,16);
const iso=v=>v?new Date(v+':00+03:00').toISOString():null;
async function rows(table){let all=[];for(let n=0;;n+=1000){let query=window.supabaseClient.from(table).select(table==='arac_bakimlari'?'id,arac_id,bakim_plan_id,km,islem_zamani,islem_tarihi,olusturma_tarihi':'*');if(table==='arac_bakimlari')query=query.not('bakim_plan_id','is',null);if(table==='yakit_takip'){const first=state.fuelRefs.map(r=>r.tarih).sort()[0];if(!first)return [];query=query.gte('tarih',first);}const r=await query.range(n,n+999);if(r.error)throw r.error;all.push(...r.data);if(r.data.length<1000)return all;}}
async function save(query){const r=await query;if(r.error)throw r.error;return r.data;}
async function gps(body){const session=await window.supabaseClient.auth.getSession();const token=session.data?.session?.access_token;if(!token)throw new Error('Oturum gerekli.');const response=await fetch('/api/maintenance-gps',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||'GPS alınamadı.');return result;}
function current(vehicle){const ref=state.refs.find(r=>r.arac_id===vehicle.id&&r.aktif);const reading=ref&&state.gps.find(r=>r.referans_id===ref.id);const fresh=reading?.durum==='ready'&&Date.now()-Date.parse(reading.hesaplanan_an)<36*3600000;return {ref,reading,km:fresh?number(reading.km):null};}
function selected(){return state.vehicles.find(v=>v.id===$('maintenance-plan-vehicle')?.value);}
function dialog(title,html,onSave){let d=$('maintenance-setup-dialog');if(!d){d=document.createElement('dialog');d.id='maintenance-setup-dialog';d.className='maintenance-setup-dialog';document.body.append(d);}d.innerHTML='<form><h2>'+esc(title)+'</h2>'+html+'<p class="setup-status" role="status"></p><footer><button type="button" class="btn-secondary">Kapat</button><button type="submit" class="btn-primary">Kaydet</button></footer></form>';let busy=false;d.oncancel=e=>{if(busy)e.preventDefault();};d.querySelector('button[type=button]').onclick=()=>{if(!busy)d.close();};d.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const data=new FormData(e.target);d.querySelectorAll('button').forEach(b=>b.disabled=true);try{await onSave(data);d.close();await window.loadMaintenancePlans();}catch(error){d.querySelector('.setup-status').textContent=error.message;}finally{busy=false;d.querySelectorAll('button').forEach(b=>b.disabled=false);}};d.showModal();}
function field(label,name,type,value='',extra=''){return '<label>'+esc(label)+'<input name="'+name+'" type="'+type+'" value="'+esc(value)+'" '+extra+'></label>';}
window.loadMaintenancePlans=async function(){if(!$('maintenance-plan-panel')||!window.supabaseClient)return;const request=++state.request;try{const data=await Promise.all(['araclar','arac_km_referanslari','arac_gps_durumlari','arac_bakim_planlari','arac_bakimlari','arac_yakit_referanslari'].map(rows));if(request!==state.request)return;[state.vehicles,state.refs,state.gps,state.plans,state.services,state.fuelRefs]=data;state.fuel=await rows('yakit_takip');if(request!==state.request)return;const select=$('maintenance-plan-vehicle'),old=select.value;const ownership=$('maintenance-plan-ownership').value;select.innerHTML='<option value="">Araç seçin</option>'+state.vehicles.filter(v=>v.mulkiyet_durumu===ownership).sort((a,b)=>a.plaka.localeCompare(b.plaka,'tr')).map(v=>'<option value="'+esc(v.id)+'">'+esc(v.plaka)+'</option>').join('');select.value=old;render();}catch(e){$('maintenance-plan-results').textContent='Bakım planları yüklenemedi: '+e.message;}};
function render(){
 const vehicle=selected();$('maintenance-plan-controls').hidden=!vehicle;
 $('maintenance-gps-status').textContent=vehicle?(()=>{const c=current(vehicle);return c.ref?(c.reading?'GPS hesabı: '+fmt(c.reading.km)+' km · Hesaplanan tarih/saat: '+date(c.reading.hesaplanan_an)+' · '+(c.km!==null?'Güncel':c.reading.hata||'Güncelleme bekliyor'):'Referans kayıtlı; GPS güncellemesi bekleniyor.'):'GPS referansı henüz yok. Sistemde kayıtlı: '+fmt(vehicle.guncel_km)+' km; ölçüm tarihi doğrulanmalı.';})():'';
 const scope=$('maintenance-plan-ownership').value,filter=$('maintenance-plan-status').value;
 let plans=state.plans.filter(p=>p.aktif&&state.vehicles.some(v=>v.id===p.arac_id&&v.mulkiyet_durumu===scope)&&(!vehicle||p.arac_id===vehicle.id));
 const views=plans.map(plan=>{const v=state.vehicles.find(v=>v.id===plan.arac_id),c=current(v);const latest=state.services.filter(b=>b.bakim_plan_id===plan.id).sort((a,b)=>String(b.islem_zamani||b.islem_tarihi).localeCompare(String(a.islem_zamani||a.islem_tarihi))||String(b.olusturma_tarihi).localeCompare(String(a.olusturma_tarihi)))[0];const serviceKm=latest?number(latest.km):number(plan.ilk_bakim_km),serviceAt=latest?(latest.islem_zamani||latest.islem_tarihi+'T12:00:00+03:00'):plan.ilk_bakim_zamani;const result=window.MaintenanceTracking.maintenanceStatus({currentKm:c.km,serviceKm,serviceAt,intervalKm:number(plan.km_araligi),intervalDays:number(plan.gun_araligi),asOf:new Date().toISOString()});let status=result.status;if(status==='current'&&((result.remainingKm!==null&&result.remainingKm<=Number(plan.uyari_km))||(result.remainingDays!==null&&result.remainingDays<=Number(plan.uyari_gun))))status='soon';return {plan,v,result,status,serviceKm,serviceAt};});
 const visible=views.filter(v=>!filter||v.status===filter);$('maintenance-plan-results').innerHTML=visible.length?visible.map(({plan,v,result,status,serviceKm,serviceAt})=>'<article class="maintenance-plan-card"><div><strong>'+esc(v.plaka)+' · '+esc(plan.tur)+(plan.konum?' · '+esc(plan.konum):'')+'</strong><span class="plan-status '+status+'">'+({due:'Bakım zamanı geldi',soon:'Yaklaşıyor',unknown:'Veri bekliyor',current:'Güncel'}[status])+'</span></div><p>Son işlem: '+fmt(serviceKm)+' km · '+esc(date(serviceAt))+'</p><p><strong>'+ (result.remainingKm===null?(plan.km_araligi?'Kilometre hesabı bekliyor':'Takvim planı'):result.remainingKm>=0?fmt(result.remainingKm)+' km kaldı':fmt(-result.remainingKm)+' km gecikti')+'</strong>'+(result.remainingDays!==null?' · '+fmt(Math.ceil(result.remainingDays))+' gün':'')+'</p><small>Aralık: '+fmt(plan.km_araligi)+' km / '+fmt(plan.gun_araligi)+' gün</small><footer><button class="btn-secondary" onclick="window.recordPlannedMaintenance(\''+esc(plan.id)+'\')">Bakımı kaydet</button><button class="btn-secondary" onclick="window.editMaintenancePlan(\''+esc(plan.id)+'\')">Planı düzenle</button></footer></article>').join(''):'<p>Bu seçim için bakım planı yok. Araç seçerek plan ekleyebilirsiniz.</p>';
 const fr=vehicle&&state.fuelRefs.find(r=>r.arac_id===vehicle.id);let text='';if(fr){const c=current(vehicle),liters=state.fuel.filter(r=>r.arac_id===vehicle.id&&String(r.tarih).slice(0,10)>fr.tarih&&String(r.tarih).slice(0,10)<=String(c.reading?.hesaplanan_an||'').slice(0,10)).reduce((s,r)=>s+Number(r.litre||0),0);const estimate=window.MaintenanceTracking.estimateFuel({anchorLiters:Number(fr.litre),capacityLiters:Number(fr.kapasite),addedLiters:liters,distanceKm:c.km===null?null:c.km-Number(fr.km),litersPer100Km:Number(fr.tuketim),completeData:fr.tum_dolumlar&&c.km!==null});text=estimate.status==='estimated'?'Tahmini yakıt: '+fmt(estimate.liters)+' litre · Tahmini menzil: '+fmt(estimate.rangeKm)+' km. Sensör ölçümü değildir.':'Yakıt tahmini için GPS / dolum bilgilerini kontrol edin.';}$('maintenance-fuel-status').textContent=text;
}
window.renderMaintenancePlans=render;
window.setupMaintenanceGPS=async function(){const vehicle=selected();if(!vehicle)return;try{const data=await gps({action:'devices'});const normalized=v=>String(v).toLocaleUpperCase('tr-TR').replace(/[^A-Z0-9ÇĞİÖŞÜ]/g,'');const candidates=data.devices.filter(d=>[d.name,d.name.split('_')[0],d.name.split('/')[0],d.name.split(' - ')[0]].some(p=>normalized(p)===normalized(vehicle.plaka)));if(candidates.length!==1)throw new Error('Plaka için tek bir GPS cihazı bulunamadı. InfoMobil cihaz/plaka eşleşmesini düzeltin.');const device=candidates[0];dialog(vehicle.plaka+' · GPS başlangıcı','<p>Cihaz: '+esc(device.name)+'. Girilen kilometrenin ölçüldüğü anı seçin. Önceki referans geçmişte korunur.</p>'+field('Gösterge kilometresi','km','number',vehicle.guncel_km??'','min="0" step="0.1" required')+field('Ölçüm tarihi / saati (Türkiye)','at','datetime-local',localNow(),'required')+field('Açıklama / düzeltme nedeni','reason','text','İlk GPS kilometre referansı','required'),async f=>{await save(window.supabaseClient.rpc('yeni_km_referansi',{p_arac:vehicle.id,p_km:Number(f.get('km')),p_an:iso(f.get('at')),p_mobile:device.id,p_neden:f.get('reason')}));});}catch(e){$('maintenance-gps-status').textContent=e.message;}};
window.syncMaintenanceGPS=async function(button){const v=selected();if(!v)return;button.disabled=true;try{const r=await gps({vehicleId:v.id});await window.loadMaintenancePlans();const result=r.results[0];if(result?.durum!=='ready')$('maintenance-gps-status').textContent=result?.hata||'Önce GPS referansı oluşturun.';}catch(e){$('maintenance-gps-status').textContent=e.message;}finally{button.disabled=false;}};
window.editMaintenancePlan=function(id){const plan=state.plans.find(p=>p.id===id),v=plan?state.vehicles.find(v=>v.id===plan.arac_id):selected();if(!v)return;dialog(v.plaka+' · Bakım planı',field('Bakım türü (örn. Yağ Değişimi, Lastik Değişimi)','type','text',plan?.tur||'Yağ Değişimi','required')+field('Konum / takım (örn. ön aks, tüm lastikler)','position','text',plan?.konum||'')+field('Bakım aralığı (km)','intervalKm','number',plan?.km_araligi??'','min="1"')+field('Bakım aralığı (gün)','intervalDays','number',plan?.gun_araligi??'','min="1" step="1"')+field('Kaç km kala uyarılsın','warnKm','number',plan?.uyari_km??1000,'min="0" required')+field('Kaç gün kala uyarılsın','warnDays','number',plan?.uyari_gun??14,'min="0" required')+field('Başlangıç: son bakım kilometresi','serviceKm','number',plan?.ilk_bakim_km??'','min="0"')+field('Başlangıç: son bakım tarihi / saati','serviceAt','datetime-local',plan?.ilk_bakim_zamani?new Date(Date.parse(plan.ilk_bakim_zamani)+10800000).toISOString().slice(0,16):'')+'<p>Aralıkları aracın bakım planına göre belirleyin. Kontrol işlemi ve parça satın almak, değişim sayacını sıfırlamaz.</p>',async f=>{const payload={arac_id:v.id,tur:String(f.get('type')).trim(),konum:String(f.get('position')).trim(),km_araligi:number(f.get('intervalKm')),gun_araligi:number(f.get('intervalDays')),uyari_km:Number(f.get('warnKm')),uyari_gun:Number(f.get('warnDays')),ilk_bakim_km:number(f.get('serviceKm')),ilk_bakim_zamani:iso(f.get('serviceAt'))};if(!payload.km_araligi&&!payload.gun_araligi)throw new Error('Kilometre veya gün aralığı gerekli.');if(payload.ilk_bakim_zamani&&Date.parse(payload.ilk_bakim_zamani)>Date.now())throw new Error('Son bakım gelecekte olamaz.');await save(plan?window.supabaseClient.from('arac_bakim_planlari').update(payload).eq('id',plan.id):window.supabaseClient.from('arac_bakim_planlari').insert([payload]));});};
window.setupMaintenanceFuel=function(){const v=selected();if(!v)return;const old=state.fuelRefs.find(r=>r.arac_id===v.id);dialog(v.plaka+' · Tahmini yakıt takibi','<p>Referansı seçtiğiniz günün sonunda, o günkü tüm dolumlardan sonra belirleyin. Sonraki dolumların tamamı yüklenmiş olmalı. Bu hesap gerçek depo sensörü değildir.</p>'+field('Depo kapasitesi (litre)','capacity','number',old?.kapasite??'','min="1" required')+field('Referans gün sonu tarihi','date','date',old?.tarih||'','required')+field('O andaki kilometre','km','number',old?.km??'','min="0" required')+field('O andaki depodaki litre','liters','number',old?.litre??'','min="0" step="0.1" required')+field('Tüketim referansı (L/100 km)','consumption','number',old?.tuketim??'','min="0.1" step="0.1" required')+'<label><input type="checkbox" name="complete" required> Sonraki tüm yakıt dolumlarını sisteme yükleyeceğim.</label>',async f=>{if(f.get('date')>=localNow().slice(0,10))throw new Error('Gün sonu referansı için tamamlanmış bir gün seçin.');await save(window.supabaseClient.from('arac_yakit_referanslari').upsert({arac_id:v.id,kapasite:Number(f.get('capacity')),tarih:f.get('date'),km:Number(f.get('km')),litre:Number(f.get('liters')),tuketim:Number(f.get('consumption')),tum_dolumlar:f.get('complete')==='on'}));});};
window.recordPlannedMaintenance=function(id){const p=state.plans.find(p=>p.id===id);if(!p)return;window._pendingMaintenancePlan=p;window.openModal('Yeni Bakım/Parça Kaydı');};
window.prepareMaintenanceTrackingForm=async function(){const vehicle=$('bakim-arac');if(!vehicle||$('bakim-plan'))return;const section=document.createElement('div');section.className='maintenance-record-filters';section.innerHTML='<label>İlgili bakım planı<select id="bakim-plan"><option value="">Plansız işlem / kontrol</option></select></label><label>Gerçek işlem saati (Türkiye)<input id="bakim-islem-saati" type="time" value="'+localNow().slice(11)+'" required></label><button type="button" class="btn-secondary" id="bakim-gps-km">İşlem anındaki KM’yi GPS’den getir</button><p id="bakim-gps-note"></p>';vehicle.closest('section').after(section);let plans=await rows('arac_bakim_planlari');const populate=()=>{$('bakim-plan').innerHTML='<option value="">Plansız işlem / kontrol</option>'+plans.filter(p=>p.arac_id===vehicle.value&&p.aktif).map(p=>'<option value="'+esc(p.id)+'">'+esc(p.tur+' '+p.konum)+'</option>').join('');$('bakim-gps-note').textContent='';$('bakim-km').value='';$('bakim-km').dataset.source='manual';};vehicle.addEventListener('change',populate);$('bakim-plan').onchange=()=>{const p=plans.find(p=>p.id===$('bakim-plan').value);if(p){const type=$('bakim-tur');if(![...type.options].some(o=>o.value===p.tur))type.add(new Option(p.tur,p.tur));type.value=p.tur;} };$('bakim-gps-km').onclick=async()=>{const button=$('bakim-gps-km');button.disabled=true;try{const at=iso($('bakim-tarih').value+'T'+$('bakim-islem-saati').value),vehicleId=vehicle.value;const r=await gps({vehicleId,at});if(vehicleId!==vehicle.value||at!==iso($('bakim-tarih').value+'T'+$('bakim-islem-saati').value))throw new Error('Araç veya işlem zamanı değişti. KM’yi yeniden getirin.');const result=r.results[0];if(result?.durum!=='ready')throw new Error(result?.hata||'GPS referansı bulunamadı.');$('bakim-km').value=Number(result.km).toFixed(1);$('bakim-km').dataset.source='gps';$('bakim-km').dataset.at=at;$('bakim-gps-note').textContent='GPS mesafesinden hesaplandı; işlem anını ve kilometreyi kontrol edin.';}catch(e){$('bakim-gps-note').textContent=e.message;}finally{button.disabled=false;}};$('bakim-km').addEventListener('input',()=>{$('bakim-km').dataset.source='manual';});populate();['bakim-tarih','bakim-islem-saati'].forEach(id=>$(id).addEventListener('change',()=>{if($('bakim-km').dataset.source==='gps'){$('bakim-km').value='';$('bakim-km').dataset.source='manual';}}));if(window._pendingMaintenancePlan){const p=window._pendingMaintenancePlan;window._pendingMaintenancePlan=null;vehicle.value=p.arac_id;populate();$('bakim-plan').value=p.id;$('bakim-plan').onchange();}};
window.collectMaintenanceTrackingFields=async function(){const plan=$('bakim-plan')?.value||null;const km=number($('bakim-km')?.value);const at=iso($('bakim-tarih').value+'T'+($('bakim-islem-saati')?.value||'12:00'));if(!Number.isFinite(Date.parse(at))||Date.parse(at)>Date.now())throw new Error('Bakım tarihi gelecekte olamaz.');if(km!==null&&(!Number.isFinite(km)||km<0))throw new Error('Geçerli kilometre girin.');if(plan){const p=await save(window.supabaseClient.from('arac_bakim_planlari').select('*').eq('id',plan).eq('arac_id',$('bakim-arac').value).single());if(!p)throw new Error('Bakım planı araçla eşleşmiyor.');if(p.tur!==$('bakim-tur').value)throw new Error('İşlem türü bakım planıyla aynı olmalı; farklı işlem için Plansız işlem seçin.');if(p.km_araligi&&km===null)throw new Error('Kilometreye göre takip edilen bakım için işlem kilometresi gerekli.');}return {bakim_plan_id:plan,km,islem_zamani:at,km_kaynagi:$('bakim-km')?.dataset.source==='gps'&&$('bakim-km').dataset.at===at?'gps':'manual'};};
})();
