-- Report-only prices. Existing operational/hakediş definitions remain untouched.
BEGIN;
CREATE TABLE public.rapor_musteri_fiyatlari (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    musteri_id uuid NOT NULL REFERENCES public.musteriler(id),
    arac_id uuid NOT NULL REFERENCES public.araclar(id),
    bolge text NOT NULL DEFAULT 'Manisa',
    donem text CHECK (donem IS NULL OR donem ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    tarife_turu text NOT NULL DEFAULT 'Vardiya',
    vardiya_fiyat numeric NOT NULL DEFAULT 0,
    tek_fiyat numeric NOT NULL DEFAULT 0,
    cikis_8_fiyat numeric NOT NULL DEFAULT 0,
    giris_2030_fiyat numeric NOT NULL DEFAULT 0,
    mesai_fiyat numeric NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX rapor_musteri_fiyatlari_scope ON public.rapor_musteri_fiyatlari
    (musteri_id, arac_id, bolge, COALESCE(donem, ''));
-- Take a one-time snapshot to preserve current report prices, including prices
-- entered before isolation. Future hakediş edits cannot change this snapshot.
INSERT INTO public.rapor_musteri_fiyatlari
(musteri_id,arac_id,bolge,donem,vardiya_fiyat,tek_fiyat,cikis_8_fiyat,giris_2030_fiyat,mesai_fiyat)
SELECT DISTINCT ON (musteri_id,arac_id,COALESCE(NULLIF(bolge,''),'Manisa'),COALESCE(donem,''))
 musteri_id,arac_id,COALESCE(NULLIF(bolge,''),'Manisa'),NULLIF(donem,''),
 COALESCE(vardiya_fiyat,0),COALESCE(tek_fiyat,0),COALESCE(cikis_8_fiyat,0),COALESCE(giris_2030_fiyat,0),COALESCE(mesai_fiyat,0)
FROM public.musteri_arac_tanimlari WHERE musteri_id IS NOT NULL
ORDER BY musteri_id,arac_id,COALESCE(NULLIF(bolge,''),'Manisa'),COALESCE(donem,''),id;
ALTER TABLE public.rapor_musteri_fiyatlari ENABLE ROW LEVEL SECURITY;
CREATE POLICY authenticated_all_access ON public.rapor_musteri_fiyatlari
FOR ALL TO authenticated USING (true) WITH CHECK (true);
REVOKE ALL ON public.rapor_musteri_fiyatlari FROM anon;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.rapor_musteri_fiyatlari TO authenticated;
GRANT USAGE,SELECT ON SEQUENCE public.rapor_musteri_fiyatlari_id_seq TO authenticated;
COMMIT;
